"use client";
import { ArrowRight } from 'lucide-react';
import type { AnalysisResult } from '@/lib/architecture/analysis-client';
import type { DiscoveryState } from '@/lib/evaluation/discovery-client';
import type { VerificationState } from '@/lib/evaluation/verification-client';
import { flowRows, nextActions, nonTechnicalItems, resultStatus, technicalStatus, type AssessmentItem } from '@/lib/overview/assessment';

type Props = { result: AnalysisResult; discovery: DiscoveryState; verification: VerificationState; analyzedAt: string; onArchitecture: () => void; onVerifications: () => void; onReanalyze: () => void };
function Assessment({item}: {item: AssessmentItem}) {
  return <article className="assessment-item"><h4>{item.title}</h4><p><span className="assessment-label">Explanation</span>{item.explanation}</p><p className="assessment-status"><span className="assessment-label">Status</span>{item.status}</p></article>;
}
export function ProjectOverview({result,discovery,verification,analyzedAt,onArchitecture,onVerifications,onReanalyze}:Props) {
  const {graph}=result;
  const ofType=(type:string)=>graph.nodes.filter(n=>n.type===type);
  const routes=ofType('API_ROUTE'), tools=ofType('TOOL'), services=ofType('EXTERNAL_SERVICE'), stores=ofType('DATASTORE');
  const flows=graph.execution_flows??[];
  const technologies=[...new Set([...ofType('FRAMEWORK').map(n=>n.label),...(flows.length?['LangGraph']:[]),...services.map(n=>n.label),...stores.map(n=>n.label)])];
  const candidates=discovery.result?.candidates??[];
  const latest=verification.status==='RESULT'?verification.result:null;
  const completed=latest?.execution_status==='COMPLETED';
  const nonTechnical=nonTechnicalItems(graph,candidates);
  const actions=nextActions(candidates,verification,nonTechnical);
  const limitations=[...new Set([...graph.limitations,...flows.flatMap(f=>f.limitations),...(discovery.result?.limitations??[]),...(latest?.limitations??[])])];
  const systemType=routes.length?(flows.length?'HTTP API with a source-declared agent workflow':'API application'):flows.length?'Application with a source-declared agent workflow':'Python repository — system role not established';
  const observed=[...(routes.length?['HTTP API entry points']:[]),...(flows.length?['Declared workflow transitions']:[]),...(tools.length?['Declared tool candidates']:[]),...(services.length?['External-service presence']:[]),...(stores.length?['Datastore presence']:[]),...(graph.edges.some(e=>e.type==='IMPORTS')?['Structural import dependencies']:[])];
  const notEstablished=[...(flows.length?['Actual execution paths and recovery behavior']:[]),...(services.length?['Service participation beyond proven call sites']:[]),...(tools.length?['Per-request tool selection and side-effect guarantees']:[]),...(candidates.some(c=>c.verification_mode!=='STATIC')?[`${candidates.filter(c=>c.verification_mode!=='STATIC').map(c=>c.name).join(', ')} require evidence beyond static architecture inspection`]:[])];
  return <main className="project-overview assessment-overview">
    <div className="page-heading"><div><h1>Overview</h1><p>Engineering assessment · {result.repository.name}</p></div><button className="secondary-button" onClick={onReanalyze}>Re-analyze Repository</button></div>
    <div className="assessment-intro"><section aria-labelledby="executive-summary"><h2 id="executive-summary">Executive Summary</h2><h3>{systemType}</h3><p>{routes.length?`The repository exposes ${routes.map(n=>n.label).join(', ')}.`:'The current projection does not establish an HTTP interface.'} {flows.length?'Supported source analysis identifies a LangGraph workflow with declared decisions and transitions. ':''}{services.length?`${services.map(n=>n.label).join(', ')} is detected as external-service presence; this alone does not prove participation in the flow.`:''}</p><div className="assessment-technologies">{technologies.map(t=><span key={t}>{t}</span>)}</div>{tools.length>0&&<p className="capability-summary">Declared capabilities: <span>{tools.map(t=>t.label.replaceAll('_',' ')).join(' · ')}</span>. Tool names describe source declarations, not proven business guarantees.</p>}</section>
    <aside className="next-action-preview"><span className="assessment-kicker">Next useful action</span><h3>{actions[0]?.title??(discovery.status==='DISCOVERING'?'Discovery in progress':discovery.status==='ERROR'?'Review discovery error':latest?'Review the recorded result':'Review the architecture and evaluation scope')}</h3><p>{actions[0]?.explanation??'No engineering conclusion is implied by architecture inspection alone.'}</p><button onClick={actions[0]?.destination==='Architecture'?onArchitecture:onVerifications}>{actions[0]?.destination==='Architecture'?'Review Source Context':actions[0]?.title.startsWith('Run ')?'Run Verification':latest?'Review Latest Result':'Review Assessments'} <ArrowRight size={14}/></button></aside></div>
    <div className="assessment-context"><section><h2>System Scope</h2><h4>Observed / In Scope</h4><p>{observed.length?observed.join(' · '):'Static Python source inspection; supported architecture facts are limited.'}</p><h4>Not Established / Not Measured</h4><p>{notEstablished.length?notEstablished.join(' · '):'No runtime measurements are provided by this static architecture analysis.'}</p></section>
    <section><div className="assessment-section-heading"><h2>How the System Works</h2><button onClick={onArchitecture}>Explore Architecture <ArrowRight size={14}/></button></div>{flows.length?<><p>Possible source-declared flow, not observed runtime execution.</p>{flows.slice(0,2).map(flow=><div className="brief-flow" key={flow.id} aria-label={flow.name}>{flowRows(flow).map((row,i)=><div className="brief-flow-row" key={i}><strong>{row.source}</strong><span aria-hidden="true">→</span><span>{row.targets.map((target,j)=><span className="brief-flow-target" key={j}>{target.condition&&<small>{target.condition} → </small>}{target.label}{j<row.targets.length-1?' / ':''}</span>)}</span></div>)}</div>)}{flows.length>2&&<p>{flows.length-2} further flows are available in Architecture.</p>}</>:<p>No supported ExecutionFlow was extracted. {graph.edges.some(e=>e.type==='IMPORTS')?'Structural imports are available in Dependency View; they do not imply runtime execution.':'Detected components describe presence only; a data-flow relationship is not established.'}</p>}</section></div>
    <section className="assessment-section components-brief"><h2>Key System Components</h2><div>{[{title:'API',nodes:routes,extra:ofType('FRAMEWORK').map(n=>n.label).join(' · ')},{title:'Workflow',nodes:[],extra:flows.length?`LangGraph · ${flows.length} declared flow${flows.length===1?'':'s'}`:''},{title:'External services',nodes:services},{title:'Declared tools',nodes:tools},{title:'Data',nodes:stores}].filter(group=>group.nodes.length||group.extra).map(group=><p key={group.title}><strong>{group.title}</strong><span>{group.extra}{group.extra&&group.nodes.length?' · ':''}{group.title==='Declared tools'?`${tools.length} candidate tools; no ordering or per-request selection implied`:group.nodes.map(n=>n.label).join(' · ')}</span></p>)}</div><small>{graph.nodes.length} projected components · {graph.edges.filter(e=>e.type==='IMPORTS').length} structural import relationships</small></section>
    <section className="assessment-section"><div className="assessment-section-heading"><h2>Engineering Assessment</h2><button onClick={onVerifications}>View Verifications <ArrowRight size={14}/></button></div><div className={`assessment-groups${candidates.length ? '' : ' no-technical'}`}><section aria-labelledby="technical-assessment"><h3 id="technical-assessment">Technical Assessment</h3><p className="assessment-group-description">Properties identified by server-validated evaluation discovery.</p>{candidates.map(c=><Assessment key={c.id} item={{title:c.name,explanation:c.reason,status:technicalStatus(c,verification)}}/>)}{!candidates.length&&<p role={discovery.status==='ERROR'?'alert':'status'}>{discovery.status==='DISCOVERING'?'Discovering verifications…':discovery.status==='ERROR'?discovery.error:discovery.status==='EMPTY'?'No supported evaluation was selected.':'No evaluations have been collected for this session.'}</p>}</section>
    <section aria-labelledby="non-technical-assessment"><h3 id="non-technical-assessment">Non-Technical Assessment</h3><p className="assessment-group-description">Operational context, not engineering verification conclusions.</p><div className="nontechnical-items">{nonTechnical.map(item=><Assessment key={item.title} item={item}/>)}</div>{!nonTechnical.length&&<p>No grounded operational or governance assessment is available in the current data.</p>}</section></div></section>
    <section className="assessment-section"><h2>Verification Status</h2><p>{candidates.length} technical evaluations identified · {candidates.filter(c=>c.can_execute&&c.applicability!=='NOT_APPLICABLE'&&!(completed&&latest?.evaluation_id===c.id)).length} ready to verify · {candidates.filter(c=>!c.can_execute).length} not currently executable · {completed?'1 completed result retained in this session':'0 completed results retained in this session'}</p>{latest?<div className="assessment-latest"><h3>Latest Verification · {latest.evaluation_name}</h3><strong>{resultStatus(latest)}</strong><p>{latest.summary}</p>{completed&&latest.applicability!=='NOT_APPLICABLE'&&<p>{latest.counts.configured} configured · {latest.counts.missing} missing · {latest.counts.unknown} unknown · {latest.counts.total} inspected{latest.coverage_percent!==null?` · ${latest.coverage_percent}% confirmed coverage`:''}</p>}<button onClick={onVerifications}>View Evidence <ArrowRight size={14}/></button></div>:<p>{verification.status==='RUNNING'?'Running verification and collecting source-backed evidence…':verification.status==='ERROR'?verification.error:'Run an available verification to collect evidence.'}</p>}</section>
    <section className="assessment-section"><h2>Recommended Next Actions</h2>{actions.length?<ol className="assessment-actions">{actions.map(action=><li key={action.title}><h4>{action.title}</h4><p>{action.explanation}</p>{action.destination==='Verifications'&&<button onClick={onVerifications}>{action.title.startsWith('Run ')?'Run Verification':action.title.startsWith('Review ')?'Review Finding':'Review Required Evidence'} <ArrowRight size={14}/></button>}</li>)}</ol>:<p>{latest?'Review the recorded scope and evidence before drawing broader conclusions.':'Review Architecture and discover evaluations before choosing a verification.'}</p>}</section>
    <section className="assessment-section"><h2>Analysis Coverage &amp; Limitations</h2><ul className="coverage-list"><li>Static repository inspection and bounded architecture extraction</li>{flows.length>0&&<li>Source-grounded workflow detection</li>}{discovery.result&&<li>Evaluation discovery completed{discovery.status==='EMPTY'?' — no selections':''}</li>}{completed&&latest?.evidence.length!>0&&<li>Evidence-backed static verification</li>}</ul>{discovery.result?.input_truncated&&<p>Discovery input was truncated; the selected evaluations cover only the supplied scope.</p>}<details><summary>Analysis Limitations · View limitations ({limitations.length})</summary>{limitations.length?limitations.map(text=><p key={text}>{text}</p>):<p>No additional limitations were returned. This is not a claim of complete system coverage.</p>}</details><p className="snapshot-note">Analyzed {new Date(analyzedAt).toLocaleString()} · <code title={result.architecture_id}>Snapshot {result.architecture_id.slice(0,12)}</code> · source structure, not production telemetry</p></section>
  </main>;
}
